// <auto-generated />
using BlazorTelemetry.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorTelemetry.Sqlite.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20261002135328_TypedTelemetryStorage")]
    partial class TypedTelemetryStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BlazorTelemetry.Core.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfirmationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyNtfy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyWebhook")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Query")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SilencedUntilUtc")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Threshold")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("BlazorTelemetry.Core.DashboardDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("BlazorTelemetry.Core.Incident", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AcknowledgedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastEvaluatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ObservedValue")
                        .HasColumnType("REAL");

                    b.Property<long?>("ResolvedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Threshold")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StartedUtc");

                    b.HasIndex("AlertRuleId", "State");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("BlazorTelemetry.Core.IngestionApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExpiresUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMcpReadKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RevokedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("IngestionApplications");
                });

            modelBuilder.Entity("BlazorTelemetry.Core.NotificationDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("IncidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<long>("NextAttemptUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SentUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventKey")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptUtc");

                    b.ToTable("NotificationDeliveries");
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DroppedAttributesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScopeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeVersion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeverityNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeverityText")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpanId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasFilter("Fingerprint IS NOT NULL");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("TraceId");

                    b.HasIndex("ResourceId", "TimestampUtc");

                    b.HasIndex("TraceId", "SpanId");

                    b.ToTable("TelemetryLogs", (string)null);
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AggregationTemporality")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<bool>("CollectionsTruncated")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsMonotonic")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Maximum")
                        .HasColumnType("REAL");

                    b.Property<string>("MetricType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Minimum")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NegativeOffset")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("REAL");

                    b.Property<long>("ObservedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositiveOffset")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Scale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScopeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeVersion")
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartTimeUtc")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Sum")
                        .HasColumnType("REAL");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ZeroCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasFilter("Fingerprint IS NOT NULL");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("Name", "TimestampUtc");

                    b.HasIndex("ResourceId", "TimestampUtc");

                    b.HasIndex("Name", "ResourceId", "TimestampUtc");

                    b.ToTable("TelemetryMetrics", (string)null);
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryMetricBucket", b =>
                {
                    b.Property<long>("MetricId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("UpperBound")
                        .HasColumnType("REAL");

                    b.HasKey("MetricId", "Ordinal", "Group");

                    b.ToTable("TelemetryMetricBuckets", (string)null);
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryMetricExemplar", b =>
                {
                    b.Property<long>("MetricId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpanId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("MetricId", "Ordinal");

                    b.ToTable("TelemetryMetricExemplars", (string)null);
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryMetricQuantile", b =>
                {
                    b.Property<long>("MetricId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantile")
                        .HasColumnType("REAL");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("MetricId", "Ordinal");

                    b.ToTable("TelemetryMetricQuantiles", (string)null);
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CircuitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientAddress")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClientPort")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentSpanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolVersion")
                        .HasColumnType("TEXT");

                    b.Property<long>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Route")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerAddress")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpanKind")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlScheme")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasFilter("Fingerprint IS NOT NULL");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("TraceId");

                    b.HasIndex("ResourceId", "TimestampUtc");

                    b.HasIndex("TraceId", "SpanId");

                    b.ToTable("TelemetryRequest", (string)null);
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SdkLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("SdkName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SdkVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Hash");

                    b.HasIndex("ServiceName", "Id");

                    b.ToTable("TelemetryResources", (string)null);
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryTrace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CollectionsTruncated")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentSpanId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScopeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpanKind")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasFilter("Fingerprint IS NOT NULL");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("TraceId");

                    b.HasIndex("ResourceId", "TimestampUtc");

                    b.HasIndex("TraceId", "SpanId");

                    b.ToTable("TelemetryTraces", (string)null);
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryTraceEvent", b =>
                {
                    b.Property<long>("TraceRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("TraceRecordId", "Ordinal");

                    b.ToTable("TelemetryTraceEvents", (string)null);
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryTraceLink", b =>
                {
                    b.Property<long>("TraceRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.HasKey("TraceRecordId", "Ordinal");

                    b.ToTable("TelemetryTraceLinks", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", (string)null);
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryLog", b =>
                {
                    b.HasOne("BlazorTelemetry.Core.TelemetryResource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryMetric", b =>
                {
                    b.HasOne("BlazorTelemetry.Core.TelemetryResource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryMetricBucket", b =>
                {
                    b.HasOne("BlazorTelemetry.Core.TelemetryMetric", null)
                        .WithMany()
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryMetricExemplar", b =>
                {
                    b.HasOne("BlazorTelemetry.Core.TelemetryMetric", null)
                        .WithMany()
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryMetricQuantile", b =>
                {
                    b.HasOne("BlazorTelemetry.Core.TelemetryMetric", null)
                        .WithMany()
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryRequest", b =>
                {
                    b.HasOne("BlazorTelemetry.Core.TelemetryResource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryTrace", b =>
                {
                    b.HasOne("BlazorTelemetry.Core.TelemetryResource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryTraceEvent", b =>
                {
                    b.HasOne("BlazorTelemetry.Core.TelemetryTrace", null)
                        .WithMany()
                        .HasForeignKey("TraceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorTelemetry.Core.TelemetryTraceLink", b =>
                {
                    b.HasOne("BlazorTelemetry.Core.TelemetryTrace", null)
                        .WithMany()
                        .HasForeignKey("TraceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
