<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.6.0</Version>
    <PackageId>BlazorTelemetry</PackageId>
    <Description>Self-hosted OTLP collector and Blazor dashboard for logs, traces, metrics, and alerts.</Description>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorTelemetry.Core\BlazorTelemetry.Core.csproj" />
    <ProjectReference Include="..\BlazorTelemetry.Sqlite\BlazorTelemetry.Sqlite.csproj" />
    <ProjectReference Include="..\BlazorTelemetry.AspNetCore\BlazorTelemetry.AspNetCore.csproj" />
  </ItemGroup>

</Project>
